
function [veredict] = compare_structs(struct, loaded_struct)

    if  loaded_struct.gaze_params.foveate == struct.gaze_params.foveate  ...  
       && strcmp(loaded_struct.gaze_params.fov_type,struct.gaze_params.fov_type)  ...
       && strcmp(loaded_struct.fusion_params.output_from_model,struct.fusion_params.output_from_model)  ... 
       && loaded_struct.color_params.gamma == struct.color_params.gamma  ... 
       && loaded_struct.color_params.srgb_flag == struct.color_params.srgb_flag  ... 
       && loaded_struct.resize_params.autoresize_ds == struct.resize_params.autoresize_ds  ...
       && loaded_struct.resize_params.autoresize_nd == struct.resize_params.autoresize_nd  ...
       && loaded_struct.compute_params.model == struct.compute_params.model  ... 
       && loaded_struct.zli_params.n_membr == struct.zli_params.n_membr  ...
       && loaded_struct.zli_params.n_iter == struct.zli_params.n_iter  ... 
       && strcmp(loaded_struct.zli_params.dist_type, struct.zli_params.dist_type)  ...
       && loaded_struct.zli_params.scalesize_type == struct.zli_params.scalesize_type  ... 
       && loaded_struct.zli_params.scale2size_type == struct.zli_params.scale2size_type  ... 
       && loaded_struct.zli_params.scale2size_epsilon == struct.zli_params.scale2size_epsilon  ...
       && loaded_struct.zli_params.bScaleDelta == struct.zli_params.bScaleDelta  ... 
       && loaded_struct.zli_params.reduccio_JW == struct.zli_params.reduccio_JW  ... 
       && strcmp(loaded_struct.zli_params.normal_type, struct.zli_params.normal_type)  ... 
       && loaded_struct.zli_params.alphax == struct.zli_params.alphax ... 
       && loaded_struct.zli_params.alphay == struct.zli_params.alphay ... 
       && loaded_struct.zli_params.nb_periods == struct.zli_params.nb_periods ... 
       && loaded_struct.zli_params.normal_input == struct.zli_params.normal_input ...
       && loaded_struct.zli_params.normal_output == struct.zli_params.normal_output ...
       && loaded_struct.zli_params.normal_min_absolute == struct.zli_params.normal_min_absolute ... 
       && loaded_struct.zli_params.normal_max_absolute == struct.zli_params.normal_max_absolute ... 
       && loaded_struct.zli_params.Delta == struct.zli_params.Delta ... 
       && loaded_struct.zli_params.ON_OFF == struct.zli_params.ON_OFF ... 
       && strcmp(loaded_struct.zli_params.boundary,struct.zli_params.boundary) ...
       && loaded_struct.zli_params.normalization_power == struct.zli_params.normalization_power ...
       && loaded_struct.zli_params.kappax == struct.zli_params.kappax ...
       && loaded_struct.zli_params.kappay == struct.zli_params.kappay ...
       && loaded_struct.zli_params.shift == struct.zli_params.shift ...
       && loaded_struct.zli_params.scale_interaction == struct.zli_params.scale_interaction ... 
       && loaded_struct.zli_params.orient_interaction == struct.zli_params.orient_interaction ...
       &&  strcmp(loaded_struct.cortex_params.cm_method,struct.cortex_params.cm_method) ...
       && loaded_struct.cortex_params.a == struct.cortex_params.a ...
       && loaded_struct.cortex_params.b == struct.cortex_params.b ...
       && loaded_struct.cortex_params.lambda == struct.cortex_params.lambda  ... 
       && loaded_struct.cortex_params.cortex_width == struct.cortex_params.cortex_width  ...
       && loaded_struct.cortex_params.isoPolarGrad == struct.cortex_params.isoPolarGrad ...
       && loaded_struct.cortex_params.eccWidth == struct.cortex_params.eccWidth ...
       && loaded_struct.cortex_params.cortex_max_elong_mm == struct.cortex_params.cortex_max_elong_mm ... 
       && loaded_struct.cortex_params.cortex_max_az_mm == struct.cortex_params.cortex_max_az_mm ...
       && loaded_struct.cortex_params.mirroring == struct.cortex_params.mirroring ...
       && loaded_struct.gaze_params.redistort_periter == struct.gaze_params.redistort_periter ...  
       && loaded_struct.gaze_params.orig_width == struct.gaze_params.orig_width  ...
       && loaded_struct.gaze_params.orig_height == struct.gaze_params.orig_height  ...
       && loaded_struct.gaze_params.img_diag_angle == struct.gaze_params.img_diag_angle ...
       %&& loaded_struct.gaze_params.fov_x == struct.gaze_params.fov_x  ... 
       %&& loaded_struct.gaze_params.fov_y == struct.gaze_params.fov_y 
   
        veredict = 1;
    elseif struct.compute_params.model == -1 %when not using model, do not compare
        veredict = 1;
    else
        veredict = 0;
    end
end



